### PR TITLE
Sdk 42: Java sdk: Add support for hbase cluster creation

### PR DESCRIPTION
**Pull request by abhisheksr8**
hbase cluster creation

### CODE REVIEW

**Comment by mindprince** [comment]
This is missing a constructor change as in 99b7b6bb199bc92032059c8790b71797d2f9acfc. What's the reason for that? Also, is this available in v1.2?

**Comment by abhisheksr8** [comment]
added constructor parameter, i created hbase cluster using v1.2 and creation is successful.

**Comment by amoghmargoor** [comment]
Can you resolve the conflict for this and test it once more manually for creating hbase cluster and hadoop cluster?

**Comment by abhisheksr8** [comment]
verified by creating hbase/spark/hadoop2 clusters

**Pull request merged**
