### PR TITLE
Add name and tags fields into command to expose API response values

### PR DESCRIPTION
**Pull request by yurib**

### CODE REVIEW

**Comment by amoghmargoor** [comment]
@yurib there is a build failure with this change. Let me correct it and merge it.

**Comment by yurib** [comment]
Sure,  please do.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Thu, Nov 24, 2016 at 2:38 AM -0800, "Amogh Margoor" <notifications@github.com<mailto:notifications@github.com>> wrote:


@yurib<https://github.com/yurib> there is a build failure with this change. Let me correct it and merge it.

**Comment by amoghmargoor** [comment]
@yurib I took a closer look at PR. Adding name and tags to command is already supported and does not need any changes to Command.java. For e.g., `qdsClient.command().hive().name("SpecialName")` will work even without any changes to Command.java. You can try commenting your changes in Command.java and run your test cases and it would just pass. The reason being all commands have their respective CommandBuilder, for instance HiveCommandBuilder for Hive command which allows setting of name and tags. Was there any other requirement apart from setting name and tags for different command ?

**Comment by yurib** [comment]
The setting of the attribute does work without any changes, but the retrieval is not possible, since the com.qubole.qds.sdk.java.entities.Command
object simply doesn’t expose them. My change was to expose these values on the history API response.

But you right about the test, my test changes doesn’t test the change, I mistake the submission of attributes with retrieval, and I am not sure the how better to do it.
I did test name attribute retrieval in my solution (the tag is not testable yet, since API doesn’t return it yet - I file another bug for it):

val history = client.command.history().invoke.get
val commandHistory = history.getCommands().asScala
val lostCommandSubmission = commandHistory.find( hcmd =>
   cmd.name.equals(hcmd.getName)
   && cmd.command_type.equals(hcmd.getCommand_type)
   && cmd.query.equals(hcmd.getCommand.get("query”)) //TODO: Use unique command name and tag

)



On Nov 28, 2016, at 8:42 PM, Amogh Margoor <notifications@github.com<mailto:notifications@github.com>> wrote:


@yurib<https://github.com/yurib> I took a closer look at PR. Adding name and tags to command is already supported and does not need any changes to Command.java. For e.g., qdsClient.command().hive().name("SpecialName") will work even without any changes to Command.java. You can try commenting your changes in Command.java and run your test cases and it would just pass. The reason being all commands have their respective CommandBuilder, for instance HiveCommandBuilder for Hive command which allows setting of name and tags. Was there any other requirement apart from setting name and tags for different command ?

**Comment by amoghmargoor** [comment]
I didn't realise it was for history API earlier. Thanks for the patch, it has been submitted to master.

**Pull request closed without merging**
